export interface Question {
  id: string
  question: string
  options: string[]
  correctAnswer: number
  difficulty: "easy" | "medium" | "hard"
  testNumber: number
}

export const allQuestions: Question[] = [
  // TEST 01 - Questions faciles (1-10)
  {
    id: "t01q01",
    question: "Quelle résolution utiliser pour l'impression offset ?",
    options: ["72 dpi", "150 dpi", "300 dpi", "600 dpi"],
    correctAnswer: 2,
    difficulty: "easy",
    testNumber: 1,
  },
  {
    id: "t01q02",
    question: "Quel format conserve la transparence ?",
    options: ["JPEG", "PNG", "BMP", "TIFF uniquement"],
    correctAnswer: 1,
    difficulty: "easy",
    testNumber: 1,
  },
  {
    id: "t01q03",
    question: "Quelle est la différence entre RGB et CMJN ?",
    options: [
      "RGB pour écran, CMJN pour impression",
      "RGB pour impression, CMJN pour écran",
      "Aucune différence",
      "RGB est plus ancien",
    ],
    correctAnswer: 0,
    difficulty: "easy",
    testNumber: 1,
  },
  {
    id: "t01q04",
    question: "Qu'est-ce qu'un fichier vectoriel ?",
    options: ["Composé de pixels", "Composé de courbes mathématiques", "Uniquement en noir et blanc", "Toujours animé"],
    correctAnswer: 1,
    difficulty: "easy",
    testNumber: 1,
  },
  {
    id: "t01q05",
    question: "Quelle extension correspond à Illustrator ?",
    options: [".psd", ".ai", ".indd", ".pdf"],
    correctAnswer: 1,
    difficulty: "easy",
    testNumber: 1,
  },
  {
    id: "t01q06",
    question: "Dans Photoshop, que fait Ctrl+Shift+Alt+E ?",
    options: [
      "Exporte l'image",
      "Fusionne tous les calques visibles sur un nouveau calque",
      "Annule la dernière action",
      "Duplique le calque",
    ],
    correctAnswer: 1,
    difficulty: "easy",
    testNumber: 1,
  },
  {
    id: "t01q07",
    question: "Quelle est la taille d'un format A4 en mm ?",
    options: ["210 x 297 mm", "297 x 420 mm", "148 x 210 mm", "420 x 594 mm"],
    correctAnswer: 0,
    difficulty: "easy",
    testNumber: 1,
  },
  {
    id: "t01q08",
    question: "Qu'est-ce que le fond perdu (bleed) ?",
    options: ["Zone de sécurité", "Marge supplémentaire pour la coupe", "Erreur d'impression", "Type de papier"],
    correctAnswer: 1,
    difficulty: "easy",
    testNumber: 1,
  },
  {
    id: "t01q09",
    question: "Combien de mm de fond perdu standard ?",
    options: ["2 mm", "3 mm", "5 mm", "10 mm"],
    correctAnswer: 1,
    difficulty: "easy",
    testNumber: 1,
  },
  {
    id: "t01q10",
    question: "Qu'est-ce que la zone de sécurité ?",
    options: ["Fond perdu", "Zone où placer les éléments importants", "Marge de l'imprimeur", "Zone de coupe"],
    correctAnswer: 1,
    difficulty: "easy",
    testNumber: 1,
  },

  // TEST 01 - Questions moyennes (11-15)
  {
    id: "t01q11",
    question: "Qu'est-ce que le Delta E et quelle valeur indique une différence imperceptible ?",
    options: ["Mesure de luminosité, <2", "Différence colorimétrique, <1", "Saturation, <5", "Contraste, <10"],
    correctAnswer: 1,
    difficulty: "medium",
    testNumber: 1,
  },
  {
    id: "t01q12",
    question: "Comment simuler l'impression offset sur écran ?",
    options: [
      "Impossible",
      "Soft proofing avec profil papier/encre spécifique",
      "Réduire la luminosité",
      "Passer en CMJN",
    ],
    correctAnswer: 1,
    difficulty: "medium",
    testNumber: 1,
  },
  {
    id: "t01q13",
    question: "Comment calculer l'interlignage optimal selon la longueur de ligne ?",
    options: [
      "Toujours 120%",
      "Plus la ligne est longue, plus l'interlignage doit être important",
      "Inversement proportionnel",
      "Aucune relation",
    ],
    correctAnswer: 1,
    difficulty: "medium",
    testNumber: 1,
  },
  {
    id: "t01q14",
    question: "Qu'est-ce que le gaufrage et comment le préparer ?",
    options: [
      "Relief sans encre, fichier vectoriel avec zones définies",
      "Impression en relief avec encre",
      "Technique de découpe",
      "Effet de texture papier",
    ],
    correctAnswer: 0,
    difficulty: "medium",
    testNumber: 1,
  },
  {
    id: "t01q15",
    question: "Qu'est-ce que la composition par tiers dynamiques ?",
    options: [
      "Règle des tiers classique",
      "Adaptation de la règle des tiers selon le mouvement et la direction",
      "Division en trois couleurs",
      "Trois éléments par composition",
    ],
    correctAnswer: 1,
    difficulty: "medium",
    testNumber: 1,
  },

  // TEST 01 - Questions difficiles (16-20)
  {
    id: "t01q16",
    question: "Comment calculer et corriger une dominante colorimétrique avec les courbes ?",
    options: [
      "Ajuster toutes les courbes identiquement",
      "Analyser l'histogramme, identifier la dominante, corriger sur la courbe opposée",
      "Utiliser uniquement la saturation",
      "Augmenter le contraste général",
    ],
    correctAnswer: 1,
    difficulty: "hard",
    testNumber: 1,
  },
  {
    id: "t01q17",
    question: "Qu'est-ce que l'espace colorimétrique ProPhoto RGB et quand l'utiliser ?",
    options: [
      "Espace standard pour le web",
      "Espace étendu pour capture RAW et retouche avancée avant conversion",
      "Uniquement pour l'impression",
      "Espace obsolète",
    ],
    correctAnswer: 1,
    difficulty: "hard",
    testNumber: 1,
  },
  {
    id: "t01q18",
    question: "Comment optimiser un fichier pour l'impression offset industrielle ?",
    options: [
      "PDF/X-4, vérification trapping, linéature adaptée, profil machine",
      "JPEG haute qualité",
      "PDF standard",
      "Format natif du logiciel",
    ],
    correctAnswer: 0,
    difficulty: "hard",
    testNumber: 1,
  },
  {
    id: "t01q19",
    question: "Qu'est-ce que la technique de lentille lenticulaire ?",
    options: [
      "Objectif photographique",
      "Support créant des effets 3D ou d'animation selon l'angle",
      "Type d'impression",
      "Effet Photoshop",
    ],
    correctAnswer: 1,
    difficulty: "hard",
    testNumber: 1,
  },
  {
    id: "t01q20",
    question: "Comment diagnostiquer un problème de moiré en impression ?",
    options: [
      "Changer d'imprimante",
      "Analyser la linéature, angles de trame, résolution source",
      "Augmenter la qualité générale",
      "Utiliser uniquement des aplats",
    ],
    correctAnswer: 1,
    difficulty: "hard",
    testNumber: 1,
  },

  // TEST 02 - Questions faciles (1-10)
  {
    id: "t02q01",
    question: "Quel format est idéal pour le web avec transparence ?",
    options: ["JPEG", "PNG", "BMP", "PDF"],
    correctAnswer: 1,
    difficulty: "easy",
    testNumber: 2,
  },
  {
    id: "t02q02",
    question: "Quelle couleur est formée par C=100, M=0, J=0, N=0 en CMJN ?",
    options: ["Rouge", "Bleu", "Vert", "Noir"],
    correctAnswer: 1,
    difficulty: "easy",
    testNumber: 2,
  },
  {
    id: "t02q03",
    question: "Qu'est-ce que le crénage (kerning) ?",
    options: [
      "Espacement entre deux caractères",
      "Espacement entre les lignes",
      "Taille de la police",
      "Alignement de texte",
    ],
    correctAnswer: 0,
    difficulty: "easy",
    testNumber: 2,
  },
  {
    id: "t02q04",
    question: "Dans Illustrator, quel outil trace des courbes de Bézier ?",
    options: ["Plume", "Crayon", "Pinceau", "Ligne"],
    correctAnswer: 0,
    difficulty: "easy",
    testNumber: 2,
  },
  {
    id: "t02q05",
    question: "Quel format est adapté à une impression haute qualité ?",
    options: [".jpg", ".pdf", ".gif", ".png"],
    correctAnswer: 1,
    difficulty: "easy",
    testNumber: 2,
  },
  {
    id: "t02q06",
    question: "Quelle taille correspond à un format A3 ?",
    options: ["210 x 297 mm", "297 x 420 mm", "420 x 594 mm", "148 x 210 mm"],
    correctAnswer: 1,
    difficulty: "easy",
    testNumber: 2,
  },
  {
    id: "t02q07",
    question: "Dans Photoshop, que fait l'outil Tampon ?",
    options: ["Efface", "Duplique une zone", "Redimensionne", "Change la couleur"],
    correctAnswer: 1,
    difficulty: "easy",
    testNumber: 2,
  },
  {
    id: "t02q08",
    question: "Que signifie CMJN ?",
    options: [
      "Cyan, Magenta, Jaune, Noir",
      "Couleur, Mode, Jeu, Niveau",
      "Code, Médium, Jeu, Noir",
      "Cyan, Magenta, Jaune, Net",
    ],
    correctAnswer: 0,
    difficulty: "easy",
    testNumber: 2,
  },
  {
    id: "t02q09",
    question: "Quelle est la résolution standard pour le web ?",
    options: ["72 dpi", "150 dpi", "300 dpi", "600 dpi"],
    correctAnswer: 0,
    difficulty: "easy",
    testNumber: 2,
  },
  {
    id: "t02q10",
    question: "Qu'est-ce qu'un objet dynamique (Smart Object) ?",
    options: ["Un calque animé", "Un calque non destructif", "Un fichier vectoriel", "Un masque"],
    correctAnswer: 1,
    difficulty: "easy",
    testNumber: 2,
  },

  // Continue with more questions from other tests...
  // For brevity, I'll add a few more key questions from different tests

  // TEST 03 - Questions faciles
  {
    id: "t03q01",
    question: "Quelle extension correspond à Photoshop ?",
    options: [".ai", ".indd", ".psd", ".svg"],
    correctAnswer: 2,
    difficulty: "easy",
    testNumber: 3,
  },
  {
    id: "t03q02",
    question: "Qu'est-ce que le fond perdu (bleed) ?",
    options: ["Zone de sécurité", "Zone coupée à l'impression", "Marge supplémentaire pour la coupe", "Format papier"],
    correctAnswer: 2,
    difficulty: "easy",
    testNumber: 3,
  },
  {
    id: "t03q03",
    question: "Quel format d'image ne gère pas la transparence ?",
    options: ["PNG", "JPEG", "GIF", "TIFF"],
    correctAnswer: 1,
    difficulty: "easy",
    testNumber: 3,
  },

  // TEST 04 - Questions faciles
  {
    id: "t04q01",
    question: "Quel logiciel est spécialisé dans la mise en page ?",
    options: ["Photoshop", "Illustrator", "InDesign", "Canva"],
    correctAnswer: 2,
    difficulty: "easy",
    testNumber: 4,
  },
  {
    id: "t04q02",
    question: "Quelle couleur obtient-on en RVB avec R=0, G=0, B=0 ?",
    options: ["Blanc", "Noir", "Rouge", "Vert"],
    correctAnswer: 1,
    difficulty: "easy",
    testNumber: 4,
  },

  // TEST 05 - Questions faciles
  {
    id: "t05q01",
    question: "Quel format privilégier pour une impression de qualité photo ?",
    options: ["PNG", "TIFF", "JPEG compressé", "GIF"],
    correctAnswer: 1,
    difficulty: "easy",
    testNumber: 5,
  },
  {
    id: "t05q02",
    question: "Dans Photoshop, quel outil permet une sélection précise avec des points d'ancrage ?",
    options: ["Lasso", "Plume", "Baguette magique", "Rectangle"],
    correctAnswer: 1,
    difficulty: "easy",
    testNumber: 5,
  },

  // Add medium difficulty questions
  {
    id: "t02q11",
    question: "Qu'est-ce que la surimpression (overprint) ?",
    options: ["Impression en double", "Superposition d'encres sans découpe", "Erreur d'imprimante", "Découpe laser"],
    correctAnswer: 1,
    difficulty: "medium",
    testNumber: 2,
  },
  {
    id: "t02q12",
    question: "Quelle méthode permet d'obtenir un gris neutre en CMJN ?",
    options: ["K=50 seul", "CMY équilibrés avec K faible", "Les deux", "Aucun"],
    correctAnswer: 2,
    difficulty: "medium",
    testNumber: 2,
  },
  {
    id: "t03q12",
    question: "Quelle est la différence entre approche optique et métrique en typographie ?",
    options: [
      "Optique = ajustement visuel, Métrique = valeurs fixes",
      "Optique pour écran, Métrique pour impression",
      "Aucune différence",
      "Optique = manuel, Métrique = automatique",
    ],
    correctAnswer: 0,
    difficulty: "medium",
    testNumber: 3,
  },
  {
    id: "t04q11",
    question: "Qu'est-ce que le trapping ?",
    options: [
      "Correction de repérage entre couleurs en impression",
      "Découpe laser",
      "Ajout de bruit",
      "Déformation du texte",
    ],
    correctAnswer: 0,
    difficulty: "medium",
    testNumber: 4,
  },
  {
    id: "t05q12",
    question: "Qu'est-ce que la règle des tiers en composition ?",
    options: [
      "Division en 3 couleurs",
      "Division de l'image en 9 zones pour équilibrer",
      "3 colonnes fixes",
      "Règle typographique",
    ],
    correctAnswer: 1,
    difficulty: "medium",
    testNumber: 5,
  },

  // Add hard difficulty questions
  {
    id: "t02q16",
    question: "Qu'est-ce que la compensation du point noir ?",
    options: [
      "Supprimer le noir",
      "Ajuster les ombres pour conserver les détails",
      "Ajouter plus de noir",
      "Augmenter le contraste",
    ],
    correctAnswer: 1,
    difficulty: "hard",
    testNumber: 2,
  },
  {
    id: "t02q19",
    question: "Qu'est-ce que la séparation de fréquences en retouche photo ?",
    options: [
      "Technique qui sépare texture et couleurs",
      "Retouche des contrastes",
      "Gestion des canaux RVB",
      "Réglage audio",
    ],
    correctAnswer: 0,
    difficulty: "hard",
    testNumber: 2,
  },
  {
    id: "t03q18",
    question: "Qu'est-ce que le gaufrage ?",
    options: ["Relief sans encre, préparé avec fichier vectoriel", "Encre dorée", "Vernis sélectif", "Texture papier"],
    correctAnswer: 0,
    difficulty: "hard",
    testNumber: 3,
  },
  {
    id: "t04q17",
    question: "Qu'est-ce que la vectorisation d'image ?",
    options: [
      "Passer du texte en contours",
      "Transformer pixels en courbes mathématiques",
      "Découper une photo",
      "Changer de format",
    ],
    correctAnswer: 1,
    difficulty: "hard",
    testNumber: 4,
  },
  {
    id: "t05q20",
    question: "Comment gérer les couleurs hors gamut tout en gardant l'intention artistique ?",
    options: [
      "Les supprimer",
      "Compression perceptuelle + retouches manuelles",
      "Les transformer en noir",
      "Les saturer",
    ],
    correctAnswer: 1,
    difficulty: "hard",
    testNumber: 5,
  },

  // Add more questions to reach sufficient pool for randomization
  // TEST 06-10 questions (adding key ones for variety)
  {
    id: "t06q01",
    question: "Quelle est la taille d'un format A1 ?",
    options: ["420 × 594 mm", "594 × 841 mm", "841 × 1189 mm", "297 × 420 mm"],
    correctAnswer: 1,
    difficulty: "easy",
    testNumber: 6,
  },
  {
    id: "t07q01",
    question: "Quelle est la taille d'un format A0 ?",
    options: ["841 × 1189 mm", "594 × 841 mm", "420 × 594 mm", "210 × 297 mm"],
    correctAnswer: 0,
    difficulty: "easy",
    testNumber: 7,
  },
  {
    id: "t08q01",
    question: "Quelle est la taille d'un format A8 ?",
    options: ["52 × 74 mm", "74 × 105 mm", "105 × 148 mm", "210 × 297 mm"],
    correctAnswer: 0,
    difficulty: "easy",
    testNumber: 8,
  },
  {
    id: "t09q01",
    question: "Quelle est la taille d'un format A7 ?",
    options: ["74 × 105 mm", "105 × 148 mm", "148 × 210 mm", "210 × 297 mm"],
    correctAnswer: 0,
    difficulty: "easy",
    testNumber: 9,
  },
  {
    id: "t10q01",
    question: "Quelle est la taille d'un format A2 ?",
    options: ["297 × 420 mm", "420 × 594 mm", "594 × 841 mm", "210 × 297 mm"],
    correctAnswer: 1,
    difficulty: "easy",
    testNumber: 10,
  },

  // Add more medium and hard questions from various tests
  {
    id: "t06q16",
    question: "Qu'est-ce que la linéarisation en gestion couleur ?",
    options: [
      "Redresser les courbes",
      "Compensations des non-linéarités d'un périphérique",
      "Supprimer le noir",
      "Aligner les typos",
    ],
    correctAnswer: 1,
    difficulty: "hard",
    testNumber: 6,
  },
  {
    id: "t07q16",
    question: "Qu'est-ce que l'espace colorimétrique Lab ?",
    options: [
      "Espace limité RVB",
      "Espace perceptuel basé sur luminosité et axes couleurs",
      "Profil ICC",
      "Gamut réduit",
    ],
    correctAnswer: 1,
    difficulty: "hard",
    testNumber: 7,
  },
  {
    id: "t08q17",
    question: 'Qu\'est-ce que le "Delta E" ?',
    options: [
      "Différence colorimétrique mesurable",
      "Unité de saturation",
      "Résolution d'écran",
      "Niveau de contraste",
    ],
    correctAnswer: 0,
    difficulty: "hard",
    testNumber: 8,
  },
  {
    id: "t09q18",
    question: 'Qu\'est-ce que la "séparation de fréquences" permet ?',
    options: [
      "Corriger texture et couleur séparément",
      "Créer un flou",
      "Ajuster le contraste",
      "Convertir en noir et blanc",
    ],
    correctAnswer: 0,
    difficulty: "hard",
    testNumber: 9,
  },
  {
    id: "t10q20",
    question: 'Qu\'est-ce que la "veille technologique active" en design ?',
    options: [
      "Lire 1 ou 2 blogs",
      "Analyse systématique des innovations et tests réguliers",
      "Attendre que les concurrents innovent",
      "Ignorer les nouvelles tendances",
    ],
    correctAnswer: 1,
    difficulty: "hard",
    testNumber: 10,
  },
]
